CLASS LHC_ZUUID_LEVEL_2_ET DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATESEMANTICKEY2 FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  zuuid_level_2_ET~CalculateSemanticKey2 .
ENDCLASS.

CLASS LHC_ZUUID_LEVEL_2_ET IMPLEMENTATION.
  METHOD CALCULATESEMANTICKEY2.
  ENDMETHOD.
ENDCLASS.
