CLASS LHC_ZUUID_LEVEL_3_ET DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATESEMANTICKEY3 FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  zuuid_level_3_ET~CalculateSemanticKey3 .
ENDCLASS.

CLASS LHC_ZUUID_LEVEL_3_ET IMPLEMENTATION.
  METHOD CALCULATESEMANTICKEY3.
  ENDMETHOD.
ENDCLASS.
