CLASS LHC_ENTITY DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEUUID FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  Entity~CalculateUUID .
ENDCLASS.

CLASS LHC_ENTITY IMPLEMENTATION.
  METHOD CALCULATEUUID.
  ENDMETHOD.
ENDCLASS.
