CLASS LHC_ATTRIBUTE DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEUUID FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  Attribute~CalculateUUID .
ENDCLASS.

CLASS LHC_ATTRIBUTE IMPLEMENTATION.
  METHOD CALCULATEUUID.
  ENDMETHOD.
ENDCLASS.
