CLASS LHC_RELATION DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEUUID FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  Relation~CalculateUUID .
ENDCLASS.

CLASS LHC_RELATION IMPLEMENTATION.
  METHOD CALCULATEUUID.
  ENDMETHOD.
ENDCLASS.
