CLASS lhc_ZI_GPI_OU2ACTOR DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PUBLIC SECTION.
    METHODS get_actor_id_from_Row_id
      IMPORTING
        im_row_uuid       TYPE SYSUUID_X16
      RETURNING
        value(ret_result) TYPE SYSUUID_X16..
  PRIVATE SECTION.

    METHODS GET_INSTANCE_AUTHORIZATIONS FOR INSTANCE AUTHORIZATION
      IMPORTING KEYS REQUEST REQUESTED_AUTHORIZATIONS FOR ZI_GPI_OU2ACTOR RESULT RESULT.

    METHODS AddToPlanning FOR MODIFY
      IMPORTING KEYS FOR ACTION ZI_GPI_OU2ACTOR~AddToPlanning.

ENDCLASS.

CLASS lhc_ZI_GPI_OU2ACTOR IMPLEMENTATION.

  METHOD GET_INSTANCE_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD AddToPlanning.
    DATA Lo_Planning_Theo TYPE REF TO  ZCLS_GPI_PLANNING_THEORICAL.
    DATA Lv_PlanningTheo_UUID TYPE  SYSUUID_X16 .
    DATA Lv_Learner_UUID TYPE  SYSUUID_X16 .
    IF  LINES( KEYS ) > 0.
      Lv_PlanningTheo_UUID = KEYS[ 1 ]-%PARAM-uuid_Planning_theo.
      Lo_Planning_Theo     = ZCLS_GPI_PLANNING_THEORICAL=>GET_INSTANCE_FROM_ID( LV_PLANNINGTHEO_UUID ).
      loop at KEYS into Data(Ls_Key).
           Lv_Learner_UUID = me->GET_ACTOR_ID_FROM_ROW_ID(  LS_KEY-Uuid ).
           Lo_Planning_Theo->ADD_LEARNER( Lv_Learner_UUID ).
      endloop.
    ENDIF.
  ENDMETHOD.


  METHOD get_actor_id_from_Row_id.
    READ ENTITIES OF ZI_GPI_OU2ACTOR
    ENTITY ZI_GPI_OU2ACTOR
    ALL FIELDS WITH VALUE #( ( Uuid = IM_ROW_UUID ) )
    RESULT DATA(LT_Result).
    if lines( LT_RESULT ) > 0.
     RETURN LT_RESULT[ 1 ]-UuidActor.
    endif.
  ENDMETHOD.

ENDCLASS.
